version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - greenride-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: greenride-backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/greenride?authSource=admin
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRE=30d
      - CLIENT_URL=http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - greenride-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: greenride-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - greenride-network

networks:
  greenride-network:
    driver: bridge

volumes:
  mongodb_data:
